### ISSUE TITLE
Not able to create a line break

### ISSUE THREAD

**Issue by eriktobben** [gahlawat/laravel-slack#1]
Hi!

I am looking at the Slack API docs, and found out that I can use \n for creating a new line break. This does not work, and the \n is displayed in Slack. I've also tried with \n as someone suggested, but that gives the same result.

Does anyone know how to create a line break?

**Comment by gahlawat** [comment]
Sorry for the late reply, I have tested this and it seems fine to me.
Please note that when you are sending a '\n' (enclosed in single quotes i.e. strict mode), it will be printed as it is, whereas if you send it as "\n" (double quotes), it will tell php to interpolate this string and use the escape character \n as a new line character.

I hope this solves your problem.
Thanks for asking though! Happy Slacking :)
