### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by samdervis** [gahlawat/laravel-slack#3]
Is it possible to specify the channel to post to.

**Comment by gahlawat** [comment]
Yes, channel as well as private user messaging support has been added as fourth parameter in send call. Please refer readme for details.

**Comment by samdervis** [comment]
Now you broke all my apps.
![image](https://user-images.githubusercontent.com/25820084/38139675-2af4ec4c-3439-11e8-809b-ec8cb2d528cd.png)

 I have been debugging my app since i pulled the new update. I had to remove each package one by one until i removed this package and everything worked. I realized you are overwriting all the config with your slack configuration. See screenshot below.

![image](https://user-images.githubusercontent.com/25820084/38139492-422940da-3438-11e8-967d-991fe08f0a50.png)
I had to go back to previous version

![image](https://user-images.githubusercontent.com/25820084/38139532-79b093fa-3438-11e8-93ea-c38bb9080cc3.png)

**Comment by gahlawat** [comment]
Oh! I tested it, worked fine for me. Can you please let me know more details about error and your version of Laravel?

**Comment by gahlawat** [comment]
@samueldervis I have pushed update 2.1.1, kindly update and let me know if your issue is resolved.

**Comment by samdervis** [comment]
https://github.com/gahlawat/laravel-slack/blob/2.1/src/Helpers/functions.php#L3
It seems this `config` function was overriding the laravel `config`. 
It is working now, thanks.
